### ISSUE TITLE
mkdir fails

### ISSUE THREAD

**Issue by cutaway** [jedisct1/crits-docker#1]
The mkdir commands to create directories in the /etc/services directory fail. I receive the following error:

`
Step 10 : RUN mkdir /etc/services/tokumx
 ---> Running in 26c25eeb133d
mkdir: cannot create directory '/etc/services/tokumx': Not a directory
The command '/bin/sh -c mkdir /etc/services/tokumx' returned a non-zero code: 1
`
I have tried several things to resolve this issue but nothing seems to work. It doesn't seem to be associated with the user as the user is root at this part of the script. The permissions for the "services" directory do seem to be too restrictive, but changing them to 755 does not help.

Sorta at my wits end. Need to step away and think about this. I'm hoping you might know the issue.

cutaway

**Comment by jedisct1** [comment]
This is not really expected since this command is not present anywhere in the [Dockerfile](https://github.com/jedisct1/crits-docker/blob/master/Dockerfile).

The fix is to add `-p`: `mkdir -p /etc/services/tokumx`, but the image already has `-p` with all `mkdir` commands.

The image on the Docker hub should be automatically updated, but it looks like something went wrong in the previous build. I manually forced it to make a new build.

**Comment by jedisct1** [comment]
Actually, there was a typo: `services` should be `service`.

This has been fixed on Github; the Docker hub is building the new image.

Thanks a lot for reporting this.
